const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 4000;

const mimeTypes = {
  '.html': 'text/html',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.wav': 'audio/wav',
  '.mp4': 'video/mp4',
  '.woff': 'application/font-woff',
  '.ttf': 'application/font-ttf',
  '.eot': 'application/vnd.ms-fontobject',
  '.otf': 'application/font-otf',
  '.wasm': 'application/wasm',
  '.mp3': 'audio/mpeg'
};

const server = http.createServer((req, res) => {
  console.log(`${req.method} ${req.url}`);

  // ─── ربط قاعدة البيانات من لوحة التحكم: حفظ إعدادات Firebase ───
  if (req.method === 'POST' && req.url.split('?')[0] === '/save-config') {
    let body = '';
    req.on('data', (chunk) => { body += chunk; });
    req.on('end', () => {
      try {
        const payload = JSON.parse(body || '{}');
        const cfg = payload && payload.config ? payload.config : null;
        const safeCfg = sanitizeConfig(cfg);
        const dataFile = '// ==========================================================\n' +
          '// Firebase DB config - auto-generated by ElMistar control panel.\n' +
          '// Do NOT edit manually. This file is rewritten when you link a DB.\n' +
          '// ==========================================================\n' +
          'window.__ELMISTAR_EMBEDDED_CONFIG = ' + JSON.stringify(safeCfg) + ';\n';
        fs.writeFile(path.join(__dirname, 'firebase-config-data.js'), dataFile, 'utf8', (err) => {
          if (err) {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ ok: false, error: err.message }));
            return;
          }
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ ok: true, config: safeCfg }));
        });
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: err.message }));
      }
    });
    return;
  }

  let filePath = '.' + req.url.split('?')[0];
  if (filePath === './') {
    filePath = './index.html';
  }

  const extname = String(path.extname(filePath)).toLowerCase();
  const contentType = mimeTypes[extname] || 'application/octet-stream';

  fs.readFile(filePath, (error, content) => {
    if (error) {
      if(error.code == 'ENOENT'){
        res.writeHead(404, { 'Content-Type': 'text/html' });
        res.end('<h1>404 Not Found</h1>', 'utf-8');
      }
      else {
        res.writeHead(500);
        res.end('Sorry, check with the site admin for error: '+error.code+' ..\n');
      }
    }
    else {
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(content, 'utf-8');
    }
  });

});

// قبول قيم الإعدادات النصية فقط (حماية بسيطة)
function sanitizeConfig(cfg) {
  if (!cfg || typeof cfg !== 'object') return null;
  const allowed = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId', 'measurementId', 'sheetsLink'];
  const out = {};
  allowed.forEach((key) => {
    if (typeof cfg[key] === 'string' && cfg[key].trim()) out[key] = cfg[key].trim();
  });
  if (!out.apiKey || !out.projectId) return null;
  return out;
}

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
